sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out2
    username: root
    password: 123456

  #阿里云oss
  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI5tLUjmf3VgbDBoKBcAwc
      accessKeySecret: 7jYJptQOOjqMA9pDrVJlXuncpPgkfr
      bucketName: web-tilas-rlmas

